"""empty message

Revision ID: 5f5de36901dc
Revises: 
Create Date: 2022-08-16 15:48:45.919246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5de36901dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    op.drop_table('employee')
    op.drop_table('detail')
    op.drop_table('emp')
    op.drop_table('employees')
    op.drop_table('departments')
    op.drop_table('customers')
    op.drop_table('master')
    op.drop_table('exsalary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exsalary',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('years_of_experience', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='exsalary_pkey')
    )
    op.create_table('master',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('master_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='master_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('customer_id', name='customers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('dept_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='departments_pkey'),
    sa.UniqueConstraint('dept_name', name='departments_dept_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('years_of_experience', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dept_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dept_name'], ['departments.dept_name'], name='fk_department', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='employees_pkey')
    )
    op.create_table('emp',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='emp_pkey')
    )
    op.create_table('detail',
    sa.Column('master_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detail_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], name='detail_master_id_fkey')
    )
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('years_of_experience', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employee_pkey'),
    sa.UniqueConstraint('title', name='employee_title_key')
    )
    op.create_table('contacts',
    sa.Column('contact_id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name='fk_customer'),
    sa.PrimaryKeyConstraint('contact_id', name='contacts_pkey')
    )
    # ### end Alembic commands ###
